### PR TITLE
Fix explicit KryoSerializer to have higher prio than implicit choices.

### LINKED ISSUE #771: Explicit Serializer directives should be used.
If you have a class that implementes/extends two classes/interfaces for which a predefined DefaulSerializer is available the priority is always a point for discussion.
However the KryoSerializable is one which is to be considered an "explicit" serializer choice.
At this moment if you have a class that does 
`class MyCustomMap extends TreeMap<String, String> implements KryoSerializable {`
then for some reason the serializer for the TreeMap 'wins' which I consider to be bad.

See https://github.com/nielsbasjes/BugReport-KryoMap

### PR DESCRIPTION
**Pull request by nielsbasjes**
This is my first attempt to fix #771
Note that I'm not sure if there are any side effects of changing the ordering in the list of defaults.
So please review this thoroughly. 

I have included a set of tests that verifies all scenarios I could think of in this area.

### CODE REVIEW

File: src/com/esotericsoftware/kryo/Kryo.java [hunk 1]
```diff
@@ -374,6 +374,10 @@ public Serializer getDefaultSerializer (Class type) {
 		Serializer serializerForAnnotation = getDefaultSerializerForAnnotatedType(type);
 		if (serializerForAnnotation != null) return serializerForAnnotation;
 
+		if (type.isAssignableFrom(KryoSerializable.class) && type != Object.class) {
+			return new KryoSerializableSerializer();
+		}
```
Comment (theigl) [inline src/com/esotericsoftware/kryo/Kryo.java:379]: Why do we need this condition? Shouldn't the subsequent loop return a `KryoSerializableSerializer` anyway? And why the `type != Object.class`?

File: test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java [hunk 2]
```diff
@@ -0,0 +1,126 @@
...
+import static org.junit.Assert.assertEquals;
+
+/**
+ * @author Niels Basjes
+ */
+@SuppressWarnings("synthetic-access")
+public class SerializerPriorityTest {
+
+    // Dummy serializer
+    public static final class MyAnnotationSerializer extends Serializer<Object> {
```
Comment (theigl) [inline test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java:43]: Please make all the inner classes and interfaces package private. There is no need for them to be public and it makes the code slightly more readable.

File: test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java [hunk 3]
```diff
@@ -0,0 +1,126 @@
...
+    @DefaultSerializer(MyAnnotationSerializer.class)
+    public static final class MyAnnotatedTreeMap extends TreeMap<String, String> {    }
+
+    @DefaultSerializer(MyAnnotationSerializer.class)
+    public static final class MyAnnotatedKryoSerializable implements BaseKryoSerializable {    }
+
+    @DefaultSerializer(MyAnnotationSerializer.class)
+    public static final class MyAnnotatedTreeMapKryoSerializable extends TreeMap<String, String> implements BaseKryoSerializable {    }
+
+    private void checkCorrectSerializer(Class<?> myClass, Class<? extends Serializer<?>> expectedSerializer) {
```
Comment (theigl) [inline test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java:81]: Please move this method to the end of the test class. I'd prefer the name `assertSerializer`

File: test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java [hunk 4]
```diff
@@ -0,0 +1,126 @@
...
+    }
+
+    @Test
+    public void testKryoSerializable() {
+        checkCorrectSerializer(MyKryoSerializable.class, KryoSerializableSerializer.class);
+    }
+
+    @Test
+    public void testTreeMapKryoSerializable() {
+        // We choose that the KryoSerializable is more important than the default Serializer
```
Comment (theigl) [inline test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java:99]: Instead of comments you could also adjust the test names. Something like `testKryoSerializableSerializerHasHigherPriorityThanDefaultSerializer`. This doesn't look great but its much easier to see what's going on when the test fails.

**Review by theigl — CHANGES_REQUESTED** [review]
@nielsbasjes: Thank you for the contribution! I left some minor comments on the test code and I don't fully understand the added condition in `getDefaultSerializer`.

File: src/com/esotericsoftware/kryo/Kryo.java (hunk 1 above)
Comment (nielsbasjes) [reply src/com/esotericsoftware/kryo/Kryo.java:379]: Yes, you're right. This was wrong.

File: test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java (hunk 2 above)
Comment (nielsbasjes) [reply test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java:43]: Done

File: test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java (hunk 3 above)
Comment (nielsbasjes) [reply test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java:81]: Done

File: test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java (hunk 4 above)
Comment (nielsbasjes) [reply test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java:99]: Done.

File: src/com/esotericsoftware/kryo/Kryo.java (hunk 1 above)
Comment (nielsbasjes) [reply src/com/esotericsoftware/kryo/Kryo.java]: I simplified the fix by only moving the KryoSerializable to the end of the list.

File: test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java (hunk 4 above)
Comment (theigl) [reply test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java]: Please remove the comments now that the test names reflect the test purpose.

Apart from that LGTM.

**Comment by theigl** [comment]
> Note that I'm not sure if there are any side effects of changing the ordering in the list of defaults. So please review this thoroughly.

This should only cause side effects when someone implements `KryoSerializable` but expects the default serializer to be used. So the exact opposite of the case you are describing. Since that doesn't make a lot of sense, I think your changes are alright.

File: test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java (hunk 4 above)
Comment (nielsbasjes) [reply test/com/esotericsoftware/kryo/serializers/SerializerPriorityTest.java]: Done

**Review by theigl — APPROVED** [review]

**Comment by magro** [comment]
Great, thanks for the PR!
